name: Backstop test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # To checkout code

env:
  NODE_VERSION: "25.2.1"
  PYTHON_VERSION: "3.13"

jobs:
  backstop-tests:
    name: Visual regression tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          npm install

      - name: Install xvfb
        run: sudo apt-get install -y xvfb pandoc

      - name: Create virtual environment
        run: uv venv

      - name: Build documentation
        run: |
          source .venv/bin/activate
          uv pip install --group doc .
          xvfb-run make -C doc html

      - name: Serve documentation
        run: npx http-server -u -p 8000 ./doc/_build/html &

      - name: Check if server is up
        run: curl -I http://localhost:8000

      - name: Run BackstopJS tests
        run: |
          npm run test

      - name: Upload Backstop report (if failed)
        if: failure()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: backstop-report
          path: backstop_data/html_report


